window.eraList = [
  {
    name: "慶長",
    startYear: 1596,
    endYear: 1614,
    yomi: "けいちょう",
    startEto: "丙申",
    Etoyomi: "ひのえさる",
  },
  {
    name: "元和",
    startYear: 1615,
    endYear: 1623,
    yomi: "げんな",
    startEto: "乙卯",
    Etoyomi: "きのとう",
  },
  {
    name: "寛永",
    startYear: 1624,
    endYear: 1643,
    yomi: "かんえい",
    startEto: "癸未",
    Etoyomi: "みずのとひつじ",
  },
  {
    name: "正保",
    startYear: 1644,
    endYear: 1647,
    yomi: "しょうほう",
    startEto: "甲申",
    Etoyomi: "きのえさる",
  },
  {
    name: "慶安",
    startYear: 1648,
    endYear: 1651,
    yomi: "けいあん",
    startEto: "戊子",
    Etoyomi: "つちのえね",
  },
  {
    name: "承応",
    startYear: 1652,
    endYear: 1654,
    yomi: "じょうおう",
    startEto: "壬辰",
    Etoyomi: "みずのえたつ",
  },
  {
    name: "明暦",
    startYear: 1655,
    endYear: 1657,
    yomi: "めいれき",
    startEto: "乙未",
    Etoyomi: "きのとひつじ",
  },
  {
    name: "万治",
    startYear: 1658,
    endYear: 1660,
    yomi: "まんじ",
    startEto: "戊戌",
    Etoyomi: "つちのえいぬ",
  },
  {
    name: "寛文",
    startYear: 1661,
    endYear: 1672,
    yomi: "かんぶん",
    startEto: "辛丑",
    Etoyomi: "かのとうし",
  },
  {
    name: "延宝",
    startYear: 1673,
    endYear: 1680,
    yomi: "えんぽう",
    startEto: "庚申",
    Etoyomi: "かのえさる",
  },
  {
    name: "天和",
    startYear: 1681,
    endYear: 1683,
    yomi: "てんな",
    startEto: "辛酉",
    Etoyomi: "かのととり",
  },
  {
    name: "貞享",
    startYear: 1684,
    endYear: 1687,
    yomi: "じょうきょう",
    startEto: "甲子",
    Etoyomi: "きのえね",
  },
  {
    name: "元禄",
    startYear: 1688,
    endYear: 1703,
    yomi: "げんろく",
    startEto: "戊辰",
    Etoyomi: "つちのえたつ",
  },
  {
    name: "宝永",
    startYear: 1704,
    endYear: 1710,
    yomi: "ほうえい",
    startEto: "甲申",
    Etoyomi: "きのえさる",
  },
  {
    name: "正徳",
    startYear: 1711,
    endYear: 1715,
    yomi: "しょうとく",
    startEto: "辛卯",
    Etoyomi: "かのとう",
  },
  {
    name: "享保",
    startYear: 1716,
    endYear: 1735,
    yomi: "きょうほう",
    startEto: "丙申",
    Etoyomi: "ひのえさる",
  },
  {
    name: "元文",
    startYear: 1736,
    endYear: 1740,
    yomi: "げんぶん",
    startEto: "丙辰",
    Etoyomi: "ひのえたつ",
  },
  {
    name: "寛保",
    startYear: 1741,
    endYear: 1743,
    yomi: "かんぽう",
    startEto: "辛酉",
    Etoyomi: "かのととり",
  },
  {
    name: "延享",
    startYear: 1744,
    endYear: 1747,
    yomi: "えんきょう",
    startEto: "甲子",
    Etoyomi: "きのえね",
  },
  {
    name: "寛延",
    startYear: 1748,
    endYear: 1750,
    yomi: "かんえん",
    startEto: "戊辰",
    Etoyomi: "つちのえたつ",
  },
  {
    name: "宝暦",
    startYear: 1751,
    endYear: 1763,
    yomi: "ほうれき",
    startEto: "辛未",
    Etoyomi: "かのとひつじ",
  },
  {
    name: "明和",
    startYear: 1764,
    endYear: 1771,
    yomi: "めいわ",
    startEto: "甲申",
    Etoyomi: "きのえさる",
  },
  {
    name: "安永",
    startYear: 1772,
    endYear: 1780,
    yomi: "あんえい",
    startEto: "壬辰",
    Etoyomi: "みずのえたつ",
  },
  {
    name: "天明",
    startYear: 1781,
    endYear: 1788,
    yomi: "てんめい",
    startEto: "辛丑",
    Etoyomi: "かのとうし",
  },
  {
    name: "寛政",
    startYear: 1789,
    endYear: 1800,
    yomi: "かんせい",
    startEto: "己酉",
    Etoyomi: "つちのととり",
  },
  {
    name: "享和",
    startYear: 1801,
    endYear: 1803,
    yomi: "きょうわ",
    startEto: "辛酉",
    Etoyomi: "かのととり",
  },
  {
    name: "文化",
    startYear: 1804,
    endYear: 1817,
    yomi: "ぶんか",
    startEto: "甲子",
    Etoyomi: "きのえね",
  },
  {
    name: "文政",
    startYear: 1818,
    endYear: 1829,
    yomi: "ぶんせい",
    startEto: "戊寅",
    Etoyomi: "つちのえとら",
  },
  {
    name: "天保",
    startYear: 1830,
    endYear: 1843,
    yomi: "てんぽう",
    startEto: "庚寅",
    Etoyomi: "かのえとら",
  },
  {
    name: "弘化",
    startYear: 1844,
    endYear: 1847,
    yomi: "こうか",
    startEto: "甲辰",
    Etoyomi: "きのえたつ",
  },
  {
    name: "嘉永",
    startYear: 1848,
    endYear: 1853,
    yomi: "かえい",
    startEto: "戊申",
    Etoyomi: "つちのえさる",
  },
  {
    name: "安政",
    startYear: 1854,
    endYear: 1859,
    yomi: "あんせい",
    startEto: "甲寅",
    Etoyomi: "きのえとら",
  },
  {
    name: "万延",
    startYear: 1860,
    endYear: 1860,
    yomi: "まんえん",
    startEto: "庚申",
    Etoyomi: "かのえさる",
  },
  {
    name: "文久",
    startYear: 1861,
    endYear: 1863,
    yomi: "ぶんきゅう",
    startEto: "辛酉",
    Etoyomi: "かのととり",
  },
  {
    name: "元治",
    startYear: 1864,
    endYear: 1864,
    yomi: "げんじ",
    startEto: "甲子",
    Etoyomi: "きのえね",
  },
  {
    name: "慶応",
    startYear: 1865,
    endYear: 1867,
    yomi: "けいおう",
    startEto: "乙丑",
    Etoyomi: "きのとうし",
  },
  {
    name: "明治",
    startYear: 1868,
    endYear: 1911,
    yomi: "めいじ",
    startEto: "戊辰",
    Etoyomi: "つちのえたつ",
  },
  {
    name: "大正",
    startYear: 1912,
    endYear: 1925,
    yomi: "たいしょう",
    startEto: "壬子",
    Etoyomi: "みずのえね",
  },
  {
    name: "昭和",
    startYear: 1926,
    endYear: 1988,
    yomi: "しょうわ",
    startEto: "丙寅",
    Etoyomi: "ひのえとら",
  },
  {
    name: "平成",
    startYear: 1989,
    endYear: 2018,
    yomi: "へいせい",
    startEto: "己巳",
    Etoyomi: "つちのとみ",
  },
  {
    name: "令和",
    startYear: 2019,
    endYear: null,
    yomi: "れいわ",
    startEto: "己亥",
    Etoyomi: "つちのとい",
  },
];

window.etoList = [
  { name: "甲子", Etoyomi: "きのえね" },
  { name: "乙丑", Etoyomi: "きのとうし" },
  { name: "丙寅", Etoyomi: "ひのえとら" },
  { name: "丁卯", Etoyomi: "ひのとう" },
  { name: "戊辰", Etoyomi: "つちのえたつ" },
  { name: "己巳", Etoyomi: "つちのとみ" },
  { name: "庚午", Etoyomi: "かのえうま" },
  { name: "辛未", Etoyomi: "かのとひつじ" },
  { name: "壬申", Etoyomi: "みずのえさる" },
  { name: "癸酉", Etoyomi: "みずのととり" },
  { name: "甲戌", Etoyomi: "きのえいぬ" },
  { name: "乙亥", Etoyomi: "きのとい" },
  { name: "丙子", Etoyomi: "ひのえね" },
  { name: "丁丑", Etoyomi: "ひのとうし" },
  { name: "戊寅", Etoyomi: "つちのえとら" },
  { name: "己卯", Etoyomi: "つちのとう" },
  { name: "庚辰", Etoyomi: "かのえたつ" },
  { name: "辛巳", Etoyomi: "かのとみ" },
  { name: "壬午", Etoyomi: "みずのえうま" },
  { name: "癸未", Etoyomi: "みずのとひつじ" },
  { name: "甲申", Etoyomi: "きのえさる" },
  { name: "乙酉", Etoyomi: "きのととり" },
  { name: "丙戌", Etoyomi: "ひのえいぬ" },
  { name: "丁亥", Etoyomi: "ひのとい" },
  { name: "戊子", Etoyomi: "つちのえね" },
  { name: "己丑", Etoyomi: "つちのとうし" },
  { name: "庚寅", Etoyomi: "かのえとら" },
  { name: "辛卯", Etoyomi: "かのとう" },
  { name: "壬辰", Etoyomi: "みずのえたつ" },
  { name: "癸巳", Etoyomi: "みずのとみ" },
  { name: "甲午", Etoyomi: "きのえうま" },
  { name: "乙未", Etoyomi: "きのとひつじ" },
  { name: "丙申", Etoyomi: "ひのえさる" },
  { name: "丁酉", Etoyomi: "ひのととり" },
  { name: "戊戌", Etoyomi: "つちのえいぬ" },
  { name: "己亥", Etoyomi: "つちのとい" },
  { name: "庚子", Etoyomi: "かのえね" },
  { name: "辛丑", Etoyomi: "かのとうし" },
  { name: "壬寅", Etoyomi: "みずのえとら" },
  { name: "癸卯", Etoyomi: "みずのとう" },
  { name: "甲辰", Etoyomi: "きのえたつ" },
  { name: "乙巳", Etoyomi: "きのとみ" },
  { name: "丙午", Etoyomi: "ひのえうま" },
  { name: "丁未", Etoyomi: "ひのとひつじ" },
  { name: "戊申", Etoyomi: "つちのえさる" },
  { name: "己酉", Etoyomi: "つちのととり" },
  { name: "庚戌", Etoyomi: "かのえいぬ" },
  { name: "辛亥", Etoyomi: "かのとい" },
  { name: "壬子", Etoyomi: "みずのえね" },
  { name: "癸丑", Etoyomi: "みずのとうし" },
  { name: "甲寅", Etoyomi: "きのえとら" },
  { name: "乙卯", Etoyomi: "きのとう" },
  { name: "丙辰", Etoyomi: "ひのえたつ" },
  { name: "丁巳", Etoyomi: "ひのとみ" },
  { name: "戊午", Etoyomi: "つちのえうま" },
  { name: "己未", Etoyomi: "つちのとひつじ" },
  { name: "庚申", Etoyomi: "かのえさる" },
  { name: "辛酉", Etoyomi: "かのととり" },
  { name: "壬戌", Etoyomi: "みずのえいぬ" },
  { name: "癸亥", Etoyomi: "みずのとい" },
];
