window.eraList = [
  {
    name: "慶長",
    startYear: 1596,
    endYear: 1614,
    yomi: "けいちょう",
    startEto: "丙申（ひのえさる）",
  },
  {
    name: "元和",
    startYear: 1615,
    endYear: 1623,
    yomi: "げんな",
    startEto: "乙卯（きのとのう）",
  },
  {
    name: "寛永",
    startYear: 1624,
    endYear: 1643,
    yomi: "かんえい",
    startEto: "癸未（みずのとのひつじ）",
  },
  {
    name: "正保",
    startYear: 1644,
    endYear: 1647,
    yomi: "しょうほう",
    startEto: "甲申（きのえさる）",
  },
  {
    name: "慶安",
    startYear: 1648,
    endYear: 1651,
    yomi: "けいあん",
    startEto: "戊子（つちのえね）",
  },
  {
    name: "承応",
    startYear: 1652,
    endYear: 1654,
    yomi: "じょうおう",
    startEto: "壬辰（みずのえたつ）",
  },
  {
    name: "明暦",
    startYear: 1655,
    endYear: 1657,
    yomi: "めいれき",
    startEto: "乙未（きのとのひつじ）",
  },
  {
    name: "万治",
    startYear: 1658,
    endYear: 1660,
    yomi: "まんじ",
    startEto: "戊戌（つちのえいぬ）",
  },
  {
    name: "寛文",
    startYear: 1661,
    endYear: 1672,
    yomi: "かんぶん",
    startEto: "辛丑（かのとのうし）",
  },
  {
    name: "延宝",
    startYear: 1673,
    endYear: 1680,
    yomi: "えんぽう",
    startEto: "庚申（かのえさる）",
  },
  {
    name: "天和",
    startYear: 1681,
    endYear: 1683,
    yomi: "てんな",
    startEto: "辛酉（かのとのとり）",
  },
  {
    name: "貞享",
    startYear: 1684,
    endYear: 1687,
    yomi: "じょうきょう",
    startEto: "甲子（きのえね）",
  },
  {
    name: "元禄",
    startYear: 1688,
    endYear: 1703,
    yomi: "げんろく",
    startEto: "戊辰（つちのえたつ）",
  },
  {
    name: "宝永",
    startYear: 1704,
    endYear: 1710,
    yomi: "ほうえい",
    startEto: "甲申（きのえさる）",
  },
  {
    name: "正徳",
    startYear: 1711,
    endYear: 1715,
    yomi: "しょうとく",
    startEto: "辛卯（かのとのう）",
  },
  {
    name: "享保",
    startYear: 1716,
    endYear: 1735,
    yomi: "きょうほう",
    startEto: "丙申（ひのえさる）",
  },
  {
    name: "元文",
    startYear: 1736,
    endYear: 1740,
    yomi: "げんぶん",
    startEto: "丙辰（ひのえたつ）",
  },
  {
    name: "寛保",
    startYear: 1741,
    endYear: 1743,
    yomi: "かんぽう",
    startEto: "辛酉（かのとのとり）",
  },
  {
    name: "延享",
    startYear: 1744,
    endYear: 1747,
    yomi: "えんきょう",
    startEto: "甲子（きのえね）",
  },
  {
    name: "寛延",
    startYear: 1748,
    endYear: 1750,
    yomi: "かんえん",
    startEto: "戊辰（つちのえたつ）",
  },
  {
    name: "宝暦",
    startYear: 1751,
    endYear: 1763,
    yomi: "ほうれき",
    startEto: "辛未（かのとのひつじ）",
  },
  {
    name: "明和",
    startYear: 1764,
    endYear: 1771,
    yomi: "めいわ",
    startEto: "甲申（きのえさる）",
  },
  {
    name: "安永",
    startYear: 1772,
    endYear: 1780,
    yomi: "あんえい",
    startEto: "壬辰（みずのえたつ）",
  },
  {
    name: "天明",
    startYear: 1781,
    endYear: 1788,
    yomi: "てんめい",
    startEto: "辛丑（かのとのうし）",
  },
  {
    name: "寛政",
    startYear: 1789,
    endYear: 1800,
    yomi: "かんせい",
    startEto: "己酉（つちのとのとり）",
  },
  {
    name: "享和",
    startYear: 1801,
    endYear: 1803,
    yomi: "きょうわ",
    startEto: "辛酉（かのとのとり）",
  },
  {
    name: "文化",
    startYear: 1804,
    endYear: 1817,
    yomi: "ぶんか",
    startEto: "甲子（きのえね）",
  },
  {
    name: "文政",
    startYear: 1818,
    endYear: 1829,
    yomi: "ぶんせい",
    startEto: "戊寅（つちのえとら）",
  },
  {
    name: "天保",
    startYear: 1830,
    endYear: 1843,
    yomi: "てんぽう",
    startEto: "庚寅（かのえとら）",
  },
  {
    name: "弘化",
    startYear: 1844,
    endYear: 1847,
    yomi: "こうか",
    startEto: "甲辰（きのえたつ）",
  },
  {
    name: "嘉永",
    startYear: 1848,
    endYear: 1853,
    yomi: "かえい",
    startEto: "戊申（つちのえさる）",
  },
  {
    name: "安政",
    startYear: 1854,
    endYear: 1859,
    yomi: "あんせい",
    startEto: "甲寅（きのえとら）",
  },
  {
    name: "万延",
    startYear: 1860,
    endYear: 1860,
    yomi: "まんえん",
    startEto: "庚申（かのえさる）",
  },
  {
    name: "文久",
    startYear: 1861,
    endYear: 1863,
    yomi: "ぶんきゅう",
    startEto: "辛酉（かのとのとり）",
  },
  {
    name: "元治",
    startYear: 1864,
    endYear: 1864,
    yomi: "げんじ",
    startEto: "甲子（きのえね）",
  },
  {
    name: "慶応",
    startYear: 1865,
    endYear: 1867,
    yomi: "けいおう",
    startEto: "乙丑（きのとのうし）",
  },
  {
    name: "明治",
    startYear: 1868,
    endYear: 1911,
    yomi: "めいじ",
    startEto: "戊辰（つちのえたつ）",
  },
  {
    name: "大正",
    startYear: 1912,
    endYear: 1925,
    yomi: "たいしょう",
    startEto: "壬子（みずのえね）",
  },
  {
    name: "昭和",
    startYear: 1926,
    endYear: 1988,
    yomi: "しょうわ",
    startEto: "丙寅（ひのえとら）",
  },
  {
    name: "平成",
    startYear: 1989,
    endYear: 2018,
    yomi: "へいせい",
    startEto: "己巳（つちのとのみ）",
  },
  {
    name: "令和",
    startYear: 2019,
    endYear: null,
    yomi: "れいわ",
    startEto: "己亥（つちのとのい）",
  },
];

window.etoList = [
  "甲子（きのえね）",
  "乙丑（きのとうし）",
  "丙寅（ひのえとら）",
  "丁卯（ひのとう）",
  "戊辰（つちのえたつ）",
  "己巳（つちのとのみ）",
  "庚午（かのえうま）",
  "辛未（かのとのひつじ）",
  "壬申（みずのえさる）",
  "癸酉（みずのとのとり）",
  "甲戌（きのえいぬ）",
  "乙亥（きのとのい）",
  "丙子（ひのえね）",
  "丁丑（ひのとのうし）",
  "戊寅（つちのえとら）",
  "己卯（つちのとのう）",
  "庚辰（かのえたつ）",
  "辛巳（かのとのみ）",
  "壬午（みずのえうま）",
  "癸未（みずのとのひつじ）",
  "甲申（きのえさる）",
  "乙酉（きのとのとり）",
  "丙戌（ひのえいぬ）",
  "丁亥（ひのとのい）",
  "戊子（つちのえね）",
  "己丑（つちのとのうし）",
  "庚寅（かのえとら）",
  "辛卯（かのとのう）",
  "壬辰（みずのえたつ）",
  "癸巳（みずのとのみ）",
  "甲午（きのえうま）",
  "乙未（きのとのひつじ）",
  "丙申（ひのえさる）",
  "丁酉（ひのとのとり）",
  "戊戌（つちのえいぬ）",
  "己亥（つちのとのい）",
  "庚子（かのえね）",
  "辛丑（かのとのうし）",
  "壬寅（みずのえとら）",
  "癸卯（みずのとのう）",
  "甲辰（きのえたつ）",
  "乙巳（きのとのみ）",
  "丙午（ひのえうま）",
  "丁未（ひのとのひつじ）",
  "戊申（つちのえさる）",
  "己酉（つちのとのとり）",
  "庚戌（かのえいぬ）",
  "辛亥（かのとのい）",
  "壬子（みずのえね）",
  "癸丑（みずのとのうし）",
  "甲寅（きのえとら）",
  "乙卯（きのとのう）",
  "丙辰（ひのえたつ）",
  "丁巳（ひのとのみ）",
  "戊午（つちのえうま）",
  "己未（つちのとのひつじ）",
  "庚申（かのえさる）",
  "辛酉（かのとのとり）",
  "壬戌（みずのえいぬ）",
  "癸亥（みずのとのい）",
];
